[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "reproducible-ml-workflows"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
